In [29]:
# 1. Sukurkite tokį ndarray ir išsaugokite kintamąjame arr:
# [[5 4 3]
#  [3 2 1]
#  [1 0 6]
#  [6 5 4]]

import numpy as np

arr = np.array ( [
    [5,4,3],
    [3,2,1],
    [1,0,6],
    [6,5,4]
]
)

print(arr)



[[5 4 3]
 [3 2 1]
 [1 0 6]
 [6 5 4]]


In [8]:

# 2. Kiek dimensijų turi arr? Kokios jos?
# # arr = [[5 4 3]
# #        [3 2 1]
# #        [1 0 6]
# #        [6 5 4]]

print(len(arr.shape)) #turi 2 dimensijas
print(arr.shape) 


2
(4, 3)


In [12]:
# 3. Atspausdinkite 3-ios eilutės antrąjį narį
# # arr = [[5 4 3]
# #        [3 2 1]
# #        [1 0 6]
#     #    [6 5 4]]

print(arr[2][1])

0


In [11]:
# 4. Atspausdinkite 2-os eilutės pirmą ir antrą narius
# # arr = [[5 4 3]
# #        [3 2 1]
# #        [1 0 6]
# #        [6 5 4]]

print(arr[1][:2])

[3 2]


In [33]:
# 5. Atspausdinkite 3-ios ir 4 eilučių antrą ir trečią narius (t.y. iš viso 4 skaičius iš dešiniojo apatinio kampo)
# # arr = [[5 4 3]
# #        [3 2 1]
# #        [1 0 6]
# #        [6 5 4]]

print(arr[2:][1:]) # bandziau ieskotis, bet neradau kaip padaryti, kad 0 rodytu

[[6 5 4]]


In [41]:
# 6. Naudodami reshape() metodą pakeiskite arr taip, kad jo dimensijos būtų (6, 2)
# # arr = [[5, 4, 3],
# #        [3, 2, 1],
# #        [1, 0, 6],
# #        [6, 5, 4]]

print(arr.reshape(6,2))


[[5 2]
 [6 4]
 [1 6]
 [3 1]
 [5 3]
 [0 4]]


In [43]:
# 7. Transponuokite arr (po transponavimo shape turi būti (2, 6))
# # arr = [[5, 4, 3],
# #        [3, 2, 1],
# #        [1, 0, 6],
# #        [6, 5, 4]]

print(np.transpose(arr.reshape(6,2)))

[[5 6 1 3 5 0]
 [2 4 6 1 3 4]]


In [47]:
# 8. Padauginkite visus šio array skaičius iš 8 ir atimkite iš visų 30, išsaugokite rezultatą kintamąjame arr_2
# # arr = [[5 3 2 1 6 5]
# #        [4 3 1 0 6 4]]

arr = np.array ( [
    [5,3,2,1,6,5],
    [4,3,1,0,6,4]
]
)

print(arr)

arr_2 =(arr * 8) - 30
print(arr_2)


[[5 3 2 1 6 5]
 [4 3 1 0 6 4]]
[[ 10  -6 -14 -22  18  10]
 [  2  -6 -22 -30  18   2]]


In [49]:

# 9. Priskirkite visus neigiamus arr_2 narius kintamąjam arr_2_neg
# # arr_2 = [[ 10  -6 -14 -22  18  10]
# #        [  2  -6 -22 -30  18   2]]


arr_2_neg = arr_2[arr_2<0]
print(arr_2_neg)

[ -6 -14 -22  -6 -22 -30]


In [57]:

# 10. Atspausdinkite arr_2_neg narių sumą ir sandaugą
# # arr_2_neg = [ -6 -14 -22  -6 -22 -30]

print("Suma:", arr_2_neg.sum())
#print(np.sum(arr_2_neg)) - kuo skiriasi sita funkcija nuo pirmiau parasytos?
print("Sandauga:", arr_2_neg.prod())

Suma: -100
Sandauga: 7318080


In [54]:

# 11. Atspausdinkite arr_2_neg medianą
# # arr_2_neg = [ -6 -14 -22  -6 -22 -30]


print(np.median(arr_2_neg))




-18.0
