In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\arunas\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np


In [10]:
a_list = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

print(a_list)
print(a_list[1][1])
print( [row[1] for row in a_list])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
6
[2, 6, 10]


In [14]:
a_np = np.array( [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]
)

print(a_np)
print(type(a_np))
print(a_np[1][1]) # pirma eile ir pirmas stulpelis - row index ir column index
print(a_np[1, 1]) #toks pat rezultatas
print(a_np[:, 1])
print(a_np[:2, 1])
print(a_np[:2, 1:3])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
6
6
[ 2  6 10]
[2 6]
[[2 3]
 [6 7]]


In [20]:
print(a_np.shape) #pirmos asies dydis # 2D array
print(len(a_np.shape))

(3, 4)
2


In [16]:
array_1d = np.array( [1, 5, 55,6,7,8,9,1]) # 1D array

In [21]:
print(array_1d.shape)
print(len(array_1d.shape))
print(array_1d)

(8,)
1
[ 1  5 55  6  7  8  9  1]


In [26]:
arr_3d = np.array( [
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6] 
        ]
]
)





In [25]:
print(arr_3d)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [28]:
print(arr_3d.shape)
print(len(arr_3d))


(2, 2, 3)
2


In [35]:
x = np.random.randn(2,5,3)
print(x.shape)

(2, 5, 3)


In [36]:
py_list = [1,2,3,4,5]

print(py_list *3)



[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [37]:
np_array = np.array( [1,2,3,4,5] )

In [41]:
print(np_array * 3) #operacijos visos veikia
print(np_array / 3)
print(np_array ** 3)

[ 3  6  9 12 15]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]
[  1   8  27  64 125]


In [42]:
print(py_list)

[1, 2, 3, 4, 5]


In [52]:
py_list[2:4] = [100] # liste taip nepakeisi
print(py_list)


[1, 2, 100]


In [48]:
np_array[2:4] = 100
print(np_array)
np_array[2:4] = [100,200]
print(np_array)


[  1   2 100 100   5]
[  1   2 100 200   5]


In [53]:
#numpy speed

size = 10000

In [54]:
py_list = list(range(size))

In [56]:
np_arr=np.arange(size)

In [58]:
%%timeit # kaip greitai yra skaiciuoja si operacija daug kartu

list_rez = []
for number in py_list:
    list_rez.append(number *10)


988 µs ± 35.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [59]:
%%timeit #Jupiter tik komanda

np_rez = np_arr *10

12 µs ± 542 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [60]:
#reshape

np_array = np.arange(0,100,2) #stulpelis
print(np_array)
print(np_array.shape)



[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
(50,)


In [62]:
print(np_array.reshape( (5,10))) # is stulpelio matrica galim pasidaryti

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [63]:
print(np_array.reshape( (2,5,5)))

[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]]

 [[50 52 54 56 58]
  [60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]
  [90 92 94 96 98]]]


In [64]:
print(np_array.reshape( (10,5,-1))) #gylis, eiles, -1 kiek liko vietos sudek 

[[[ 0]
  [ 2]
  [ 4]
  [ 6]
  [ 8]]

 [[10]
  [12]
  [14]
  [16]
  [18]]

 [[20]
  [22]
  [24]
  [26]
  [28]]

 [[30]
  [32]
  [34]
  [36]
  [38]]

 [[40]
  [42]
  [44]
  [46]
  [48]]

 [[50]
  [52]
  [54]
  [56]
  [58]]

 [[60]
  [62]
  [64]
  [66]
  [68]]

 [[70]
  [72]
  [74]
  [76]
  [78]]

 [[80]
  [82]
  [84]
  [86]
  [88]]

 [[90]
  [92]
  [94]
  [96]
  [98]]]


In [65]:
print(np_array.reshape( (2,1,-1)))

[[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44
   46 48]]

 [[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
   96 98]]]


In [72]:
array_2d = np.array([[1,2], [4,3], [7,4]])
print(array_2d)


array_3d = np.array ([] 




)


[[1 2]
 [4 3]
 [7 4]]


In [73]:
# numpy methods

np.mean(array_2d)





3.5

In [78]:
print(array_2d)
print(np.mean(array_2d,axis = 0)) # stulpeliu vidurkiai
print(np.mean(array_2d,axis = 1)) # eiliu vidurkiai

[[1 2]
 [4 3]
 [7 4]]
[4. 3.]
[1.5 3.5 5.5]


In [82]:
print(np.std(array_2d, axis = 0)) #standartinis nuokrypis stulpeliu
print(np.std(array_2d)) #bendras

[2.44948974 0.81649658]
1.8929694486000912


In [86]:
print(np.sum(array_2d, axis = 0)) #stulpeliu
print(np.sum(array_2d, axis = 1)) #eiluciu


[12  9]
[ 3  7 11]


In [87]:
print(array_2d)
print(array_2d.transpose()) #apvercia aukstyn kojom



[[1 2]
 [4 3]
 [7 4]]
[[1 4 7]
 [2 3 4]]


In [88]:
#comparisons


np_array = np.arange(0,60,2)
print(np_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58]


In [89]:
np_array [np_array <30] #filtruoti kaip galima

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [90]:
np_array <30 #also called mask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [91]:
np_array [np_array % 3 == 0] #dalijasi is 3 kurie skaiciai

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])